name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.2.0]
    steps:
      - uses: actions/checkout@master
      - name: install, build, and test
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Deploy to production
        uses: mboretto/deploy-to-github-pages-action@master
        env:
          AUTHOR: mboretto
          BUILD_PATH: dist
          GITHUB_PAGE_NAME: mboretto.github.io/telegram-bot-vue-wep-app
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: mboretto
